version: '3'

services:
  crawlerdb:
    image: "postgres:14.1"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: pages
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
    ports:
      - "5432:5432"
    volumes:
      - ./crawler_data:/var/lib/postgresql/data
  indexerdb:
    image: "postgres:14.1"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5433
      POSTGRES_DB: index
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
    ports:
      - "5433:5433"
    volumes:
      - ./indexer_data:/var/lib/postgresql/data
    command: -p 5433
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: search-engine-server
    container_name: server
    depends_on:
      - crawlerdb
      - indexerdb
    environment:
      FLASK_APP: main.py
    volumes:
      - ./server:/app:z
    ports:
      - "8002:8002"


